"use client";
import { useEffect, useState } from "react";
export default function Admin() {
  const [authed, setAuthed] = useState(false); const [pw, setPw] = useState(""); const [data, setData] = useState<any>(null);
  const load = () => fetch("/api/tickets").then(r => r.json()).then(setData);
  useEffect(() => { load(); fetch("/api/admin/pago", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({}) }).then(r => { if (r.status !== 401) setAuthed(true); }).catch(() => { }); const es=new EventSource("/api/tickets/stream"); es.onmessage=e=>setData(JSON.parse(e.data)); return ()=>es.close(); }, []);
  const login = async () => { const r = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pw }) }); if (r.ok) { setAuthed(true); load(); } else alert("Senha incorreta"); };
  const act = async (numero: number, action: string) => { const r = await fetch("/api/admin/pago", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ numero, action }) }); if (!r.ok) alert((await r.json()).error); load(); };
  if (!data) return <p className="p-4">Carregando...</p>;
  if (!authed) return <div className="max-w-sm mx-auto p-4"><h2 className="font-bold mb-2">Admin</h2><input type="password" value={pw} onChange={e => setPw(e.target.value)} placeholder="senha" className="border p-2 w-full" /><button onClick={login} className="mt-2 bg-black text-white px-4 py-2 rounded w-full">Entrar</button><p className="text-xs mt-2"> (defina ADMIN_PASSWORD na Vercel)</p></div>;
  return <main className="max-w-3xl mx-auto p-4"><h2 className="font-bold mb-3">Admin - {data.config.titulo}</h2><table className="w-full border-collapse text-sm"><thead><tr><th className="border p-1">Nº</th><th className="border p-1">Status</th><th className="border p-1">Nome</th><th className="border p-1">Ações</th></tr></thead><tbody>{Array.from({ length: data.config.quantidade }, (_, i) => { const n = data.config.inicio + i, k = String(n); const st = k in data.pagos ? "Pago" : k in data.reservados ? "Reservado" : "Disponível"; const nm = data.pagos[k] || data.reservados[k] || "-"; return <tr key={n}><td className="border p-1">{String(n).padStart(3, "0")}</td><td className="border p-1">{st}</td><td className="border p-1">{nm}</td><td className="border p-1">{st === "Reservado" && <><button onClick={() => act(n, "pago")} className="bg-green-600 text-white px-2 py-1 mr-1 text-xs">Pago</button><button onClick={() => act(n, "cancelar")} className="border px-2 py-1 text-xs">Cancelar</button></>}{st === "Pago" && <button onClick={() => act(n, "reverter")} className="border px-2 py-1 text-xs">Reverter</button>}</td></tr>; })}</tbody></table><p className="mt-3"><a href="/" className="underline">← voltar</a></p></main>;
}
